-- 코드를 입력하세요
# SELECT * FROM ONLINE_SALE
# ORDER BY USER_ID

SELECT USER_ID, PRODUCT_ID
FROM ONLINE_SALE
GROUP BY USER_ID, PRODUCT_ID
# HAVING (SELECT COUNT(*) FROM ONLINE_SALE) > 1;

HAVING (COUNT(*) > 1)
# HAVING ((SELECT COUNT(PRODUCT_ID) FROM ONLINE_SALE) > 1);
# SELECT USER_ID, PRODUCT_ID
# FROM ONLINE_SALE
# WHERE (SELECT COUNT(PRODUCT_ID) FROM ONLINE_SALE)  > 1 

ORDER BY USER_ID ASC, PRODUCT_ID DESC;