-- 코드를 입력하세요
SELECT O.ANIMAL_ID, O.NAME 
FROM ANIMAL_OUTS O
LEFT JOIN
ANIMAL_INS I
ON O.ANIMAL_ID = I.ANIMAL_ID
WHERE I.ANIMAL_ID IS NULL;

SELECT ANIMAL_ID, NAME FROM
ANIMAL_OUTS WHERE ANIMAL_ID NOT IN 
(SELECT I.ANIMAL_ID 
 FROM ANIMAL_INS I INNER JOIN 
 ANIMAL_OUTS O ON
 I.ANIMAL_ID = O.ANIMAL_ID
 )