-- 코드를 입력하세요
WITH RECURSIVE number_seq(HOUR) AS (
	SELECT 0
	UNION ALL
	SELECT HOUR + 1 FROM number_seq WHERE HOUR < 23
)
SELECT HOUR, 0 AS COUNT FROM number_seq
WHERE HOUR NOT IN (
SELECT CAST(DATE_FORMAT(DATETIME, "%H") AS SIGNED) AS HOUR
FROM ANIMAL_OUTS
)
UNION SELECT CAST(DATE_FORMAT(DATETIME, "%H") AS SIGNED) AS HOUR, COUNT(*)
FROM ANIMAL_OUTS GROUP BY HOUR ORDER BY HOUR;